name: Run tests, build images and push

on: [push]

env:
  project: test

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ENVIRONMENT_NAME: [ STAG, PROD ]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: /var/lib/docker/image
          key: docker-image
      - uses: actions/cache@v1
        with:
          path: /var/lib/docker/overlay2
          key: docker-overlay2

      - shell: bash
        env:
          PROD_GOOGLE_CREDENTIALS: ${{secrets.PROD_GOOGLE_CREDENTIALS}}
          STAG_GOOGLE_CREDENTIALS: ${{secrets.STAG_GOOGLE_CREDENTIALS}}
        run: |
          GOOGLE_CREDENTIALS="${${{ matrix.ENVIRONMENT_NAME}}_GOOGLE_CREDENTIALS}"
          echo cred lines: $(echo "$GOOGLE_CREDENTIALS" | wc -l)
          
          echo "$GOOGLE_CREDENTIALS" | gcloud auth activate-service-account --key-file -

          GOOGLE_PROJECT=$(echo "$GOOGLE_CREDENTIALS" | jq -r '.project_id')
          gcloud config set project $GOOGLE_PROJECT

          export GOOGLE_APPLICATION_CREDENTIALS="$(mktemp -d)/google_credentials.json"
          echo "$GOOGLE_CREDENTIALS" > "$GOOGLE_APPLICATION_CREDENTIALS"

          docker pull busybox
          docker tag gcr.io/$GOOGLE_PROJECT/$project:$CI_COMMIT_SHA
          docker push gcr.io/$GOOGLE_PROJECT/$project:$CI_COMMIT_SHA

