name: Run tests, build images and push

on: [push]

env:
  project: test

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: /var/lib/docker/image
          key: docker-image
      - uses: actions/cache@v1
        with:
          path: /var/lib/docker/overlay2
          key: docker-overlay2

      - shell: bash
        env:
          PROD_GOOGLE_CREDENTIALS: ${{secrets.PROD_GOOGLE_CREDENTIALS}}
          STAG_GOOGLE_CREDENTIALS: ${{secrets.STAG_GOOGLE_CREDENTIALS}}
        run: |
          docker images
          docker info -f '{{json .}}'
